In [9]:
import tensorflow as tf
tf.__version__

'1.12.0'

In [10]:
hello = tf.constant("hello")
world = tf.constant("World")

In [11]:
type(hello)
type(world)
#a tensor object

tensorflow.python.framework.ops.Tensor

In [13]:
#doesn't print out content
print(hello)

#to print contents in tensors, or any any operations in tf
with tf.Session() as sess:
    result = sess.run(hello+world)

Tensor("Const_2:0", shape=(), dtype=string)


In [15]:
print(result) #b stands for bytes literal

b'helloWorld'


In [17]:
a = tf.constant(10)
b = tf.constant(20)
a+b #same as before

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result = sess.run(a+b)
result

30

In [22]:
#other operations
const = tf.constant(10)
#to fill out a matrix
fill_mat = tf.fill(dims=(4,4),value=10) #a 4x4 matrix with values of 10s
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [25]:
#making a list of operations to deal with the prev tensors
my_ops = [const, fill_mat, myzeros,myones,myrandn,myrandu]

#now run()/print() them
with tf.Session() as sess:
    for op in my_ops:
        print(sess.run(op)) #or sess.eval() can evaluate the ops also

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-2.273372   -0.27641472  0.45923766  0.8694204 ]
 [-0.34542558  0.36099058 -1.0338533   0.57333654]
 [ 1.3358229   2.3944645   2.1724205  -0.17208242]
 [-1.4644834  -1.1779041   1.1122319  -0.8425532 ]]
[[0.16005957 0.52137816 0.7657125  0.37206197]
 [0.8880484  0.65388036 0.45767164 0.11266053]
 [0.31220412 0.55290914 0.93433285 0.2316438 ]
 [0.44709754 0.2921965  0.59760046 0.7877476 ]]


In [32]:
#an example of how to do matrix multiplication in tf
a = tf.constant([[1,2],
                 [3,4]]) #2x2
b = tf.constant([[10],[100]]) #2x1

In [33]:
print(a.get_shape())
print(b.get_shape())

(2, 2)
(2, 1)


In [35]:
with tf.Session() as sess:
    result = sess.run(tf.matmul(a,b))
result

array([[210],
       [430]], dtype=int32)

# Example of TF Graph

In [38]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1+n2

with tf.Session() as sess:
    result = sess.run(n3)
    
print(result)

3


In [42]:
#default tf graph
print(tf.get_default_graph())
#we can create a different default graph
print(tf.Graph())

In [45]:
graph1 = tf.get_default_graph()
print (graph1) #memory lined up
graph2 = tf.Graph()
print(graph2) #different than the 2nd graph. Now we have 3 graphs!

In [47]:
#how to set graph2 as default graph, use as_default() attribute
with graph2.as_default():
    print(graph2 == tf.get_default_graph())

True


# Variables and Placeholders

In [48]:
#using interactive session so we dont have to use "with"
sess = tf.InteractiveSession()

In [49]:
my_tensor = tf.random_uniform((4,4),minval=0,maxval=1)
my_tensor #float 32

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [52]:
my_var = tf.Variable(initial_value = my_tensor) #weight matrix
print(my_var)
sess.run(my_var) #we need to initialize our variables before running

<tf.Variable 'Variable_2:0' shape=(4, 4) dtype=float32_ref>


FailedPreconditionError: Attempting to use uninitialized value Variable_2
	 [[{{node _retval_Variable_2_0_0}} = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_2)]]

In [57]:
#how to initalize and run the init
init = tf.global_variables_initializer()
sess.run(init)

In [58]:
sess.run(my_var)

array([[0.02651405, 0.03135598, 0.29815805, 0.43104696],
       [0.8492284 , 0.35564852, 0.16629434, 0.355098  ],
       [0.8601841 , 0.23346424, 0.8484758 , 0.46184587],
       [0.68451   , 0.97015345, 0.13798809, 0.48460138]], dtype=float32)

In [60]:
placeholder = tf.placeholder(tf.float32) #we have to tell the input shape and datatypes
placeholder

<tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>